### ISSUE TITLE
Your readme is utter garbage

### ISSUE THREAD

**Issue by Khalian** [scallop/scallop#124]
Could you please explain properly how a hello world app args can utilize scallop end to end.

You can use https://commons.apache.org/proper/commons-cli/usage.html as reference.

**Comment by ayakovlenko** [comment]
Yes, readme could be better, but have you checked project's wiki?

**Comment by ecurtin** [comment]
I found the README entirely sufficient, particularly because it contains a link to the excellent wiki:

"For more info and information on usage, you can look into the [project wiki](https://github.com/scallop/scallop/wiki) or consult the [API docs](http://scallop.github.io/scallop/#org.rogach.scallop.package)."

**Comment by Rogach** [comment]
I do agree that readme could use some improvement. Current "quick example" is a little bit too complex - I'll update it to be easier to understand.

**Comment by Khalian** [comment]
My apologies for the harsher language before. I was frustrated as I expected a very short ramp up time for a CLI parsing library.

**Comment by Rogach** [comment]
I updated the readme, hopefully it is better now. Would appreciate your opinion on it!
