### ISSUE TITLE
Trailing Arguments Work Differently in Conf vs Builder?

### ISSUE THREAD

**Issue by alexy** [scallop/scallop#2]
I've tried to convert from Builder to Conf:

https://gist.github.com/2321628

-- and Conf fails to parse the trailing arguments...  Is it in the way I use it?  I try to extract things right inside the Conf, does it mess up its state?

A+

**Comment by Rogach** [comment]
Yes, in fact extracting things before call to "verify" messes up things - because all those "opt", "props" and "trailArg" calls add options to underlying builder and return ScallopOption, which is needed to wait while the rest of options are constructed.

So when you extract the value right on-the-spot:

``` scala
val date = opt[String]("date").get
```

the whole parse process is initiated, and the parser (since it does not know about trailing args yet) tries to stuff all trailing args into -k option, and obviously fails (since -k is a flag). 

To defer the parsing process, you can use either lazy vals for extractors:

``` scala
val dateO = opt[String]("date")
lazy val date = dateO.get
```

or put all your extractors after the "verify" statement.

I edited your gist, so now the test passes - https://gist.github.com/2327210/0f0589193408b399c548ecfacca48aa07ad0d13d
