### ISSUE TITLE
Is there a reason ScallopOption is used instead of Option?

### ISSUE THREAD

**Issue by gmosx** [scallop/scallop#20]
The standard Option provides many useful methods.

**Comment by Rogach** [comment]
Yes. When you are constructing the config object:

``` scala
object Conf extends ScallopConf(Seq("-a","-b")) {
  val apples = opt[Boolean]("apples")
  val bananas = opt[Boolean]("bananas")
}
```

When you create the `apples` option, scallop does not know yet about `bananas` option, thus it can't parse the arguments to get the option value - it will result in error. So ScallopOption is, basically, a lazy option, that only evaluates it's contents on request.

Also, ScallopOption "remembers" the option name, so that you can write:

``` scala
object Conf extends ScallopConf(Seq("-a","-b")) {
  val apples = opt[Boolean]("apples")
  val bananas = opt[Boolean]("bananas")
  codependent(apples, bananas)
}
```

You can get the regular Option from ScallopOption by calling `.get`. Also, ScallopOption provides almost all methods of Option - see the [API docs](http://rogach.github.com/scallop/#org.rogach.scallop.ScallopOption). What methods are missing?

**Comment by Rogach** [comment]
I hope I answered your question, so I'm closing the issue.
