### ISSUE TITLE
Verify fails if trailing args contain options

### ISSUE THREAD

**Issue by jpork** [scallop/scallop#203]
Verification fails if the option marker -- is in present in the trailing args list. So it becomes impossible to pass arbitrary options/args to a given tool/script.  When I remove the option marker -- from `--script-opt `the test code succeeds. Otherwise it fails with `[scallop] Error: Unknown option 'script-opt'`

Trailing args should probably not be verified. It should be possible to pass arbitrary undefined options to a given tool. For instance the java command line could be an example for options in trailing args. Where --opt1 and --opt2 are just passed to the main function like so:  

`java -cp *.jar DemoMain --opt1 arg1 --opt2 arg2`

FreeSpec test:
```
"pass trailing args to script" in {
    class Conf(arguments: Seq[String]) extends ScallopConf(arguments) {
      val globalOpt = opt[String](required=false)
      val scriptName = trailArg[String](required = false)
      val scriptArgs = trailArg[List[String]](required = false)
      verify()
    }
    val conf = new Conf(Seq("--global-opt", "value", "some-script.js", "--script-opt", "value"))
    conf.globalOpt() should be("value")
    conf.scriptName() should be("some-script.js")
    conf.scriptArgs() should be(Seq("--script-opt", "value"))
  }
```

**Comment by Rogach** [comment]
Because Scallop allows multiple arguments to a single option (like `--option arg1 arg2 arg3`) it would be difficult to distinguish between actual options and trailing arguments in such cases.

To pass arbitrary contents through trailing args you can use `--` separator argument - everything after it will go straight to trailing args without any verification. (the same trick works for most other cli arg parsers)

Your example will pass the test with the following modification:

```
val conf = new Conf(Seq("--global-opt", "value", "--", "some-script.js", "--script-opt", "value"))
```

Closing this issue for now - if you have additional questions, feel free to reopen.

**Comment by Rogach** [comment]
One more point - Scallop validates the options and raises an exception to notify a user that he probably mistyped some option. If we allow any options in trailing arguments, we won't be able to distinguish mistyped options from those that are passed to other programs, and that can lead to user errors (user expected to give an option to the main program, but instead that option got passed downstream).
