### ISSUE TITLE
Tests with option name guessing sometimes fail

### ISSUE THREAD

**Issue by Rogach** [scallop/scallop#23]
Steps to reproduce:

``` bash
for x in {1..50}; do sbt test; done
```

There are about 2 crashes in such run.

**Comment by akisaarinen** [comment]
Do you have any clue why this could happen?

**Comment by Rogach** [comment]
Not yet. I'm a bit busy these days, but I'll try to solve this as fast as I can.

**Comment by Rogach** [comment]
Well, seems I'm closing in on the problem. The following command always triggers an error:

```
(echo test-only org.rogach.scallop.SubcommandsTest; echo test-only org.rogach.scallop.Usability ; echo exit) | sbt
```

As I expected, there seems to be some scary interference between tests (and the problem was not constant because ScalaTest runs test suites in random order).

**Comment by Rogach** [comment]
It seems that I've hit a problem with JVM or Scala compiler... I relied on reflection to return me the methods in their declaration order, but now I have a test that results in other behavior:

``` scala
object Conf extends ScallopConf(Seq("-b")) {
  val bananas = opt[Boolean]("bananas")
}
Conf
val conf = new ScallopConf() {
  val apples = opt[Int]()
  val bananas = opt[Int]()
}
```

In this case, the `bananas` method is returned before `apples`, thus screwing the option name guessing.

Seems that this is not the good way to detect option names, thus unless I find some other clever way to guess them, I'll have to remove the feature completely.

**Comment by Rogach** [comment]
Ok, I'm out of ideas. I'll revert the option name guessing back behind a flag (but will still keep it), since the problem is not that severe - it only would happen if you have several option configurations defined, and they have options with same names.

**Comment by Rogach** [comment]
The behavior is fixed now. (See 9d470c4c563041)

**Comment by amirshim** [comment]
This does not seem to be fixed. Every once in a while, this happens to me, and makes the guess feature unusable.

I believe that this might be happening because Java (or Scala?) is re-ordering the store instructions of the different config parameters.

For example, in:

``` scala
guessOptionName = true
val apples = opt[Int]()
val name = opt[String]()
```

"apples" is not being stored until after the "name" line is executed.  So inside the code for `opt[String]()`, the code:
https://github.com/Rogach/scallop/blob/master/src/main/scala/org.rogach.scallop/ScallopConf.scala#L111
returns apples again, and we have a name collision.

Furthermore, I'm wondering if the order of reflection's getMethods() or Scala's method ordering should be relied on for guessing?

I think a better approach would be something like this: 

https://gist.github.com/4508437

where `onVerify()` would be called during the first access, and it would use reflection to directly populate the names with no guessing. I realize this is a semi-large change to implement, but would love to see it :+1:

**Comment by Rogach** [comment]
Yes, your approach seems better. I think I can even get away without `field.setAccessible` - I can annotate _name field with private[scallop], and that should do it.

I'll try to implement it today or tomorrow, and if it will work, I'll revert guessing default back to `true`. 

Thanks for your help!

**Comment by Rogach** [comment]
@amirshim I implemented and tested the proposed change, and it would be great if you could test it as well!

I published a snapshot, if you are using sbt, here's the needed incantation:

``` scala
resolvers += "sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
libraryDependencies += "org.rogach" %% "scallop" % "0.6.5~3~SNAPSHOT"
```

**Comment by amirshim** [comment]
@Rogach Wow, that was fast.  I'll do more testing later, but can we get rid of the Randomized number on line 49: https://github.com/Rogach/scallop/blob/master/src/main/scala/org.rogach.scallop/ScallopConf.scala#L49

Can we simply have a locally private static counter somewhere, and increment it by one.  My issue is that theoretically we can have non-unique numbers when you call `gen.nextInt(1000000)` Is there a reasoning behind the randomness?

**Comment by Rogach** [comment]
Well, purely aesthetic reasons :)

Since I initialize the random generator with constant seed (0), the results are always the same - and that generator generates 449 unique numbers before first repeated value. Thus, it's just glorified (and buggy) version of that counter you propose.

I'll replace it with the counter now, since I, too, believe that it would be better.

**Comment by amirshim** [comment]
Seems fixed now, i.e. it hasn't failed today.  But I guess time will tell. Excellent job.
