### ISSUE TITLE
Support subscript args forwarding to another script without duplicating usage

### ISSUE THREAD

**Issue by ldeck** [scallop/scallop#233]
Hey, firstly — thanks for the lib!

I'm wanting to create some scripts whereby the subcommand calls out to another script. 

For example.
//foo.sh
```
class Conf(arguments: Seq[String]) extends ScallopConf(arguments) {
  object bar extends Subcommand("bar")
  addSubcommand(bar)
  ...
  verify()
}

object Main {
  def main(args: Array[String]): Unit = {
    val conf = new Conf(args.toIndexedSeq)

    conf.subcommand match {
      case Some(conf.bar) =>
        import sys.process._
        """bar ''${conf.args.tail.mkString(" ")}""".!
      ...
    }   
  }
}
```

If I call `foo bar --help` I'm seeing the help message for foo instead of bar.
Also if I pass an arbitrary option like `foo bar baz` I see "[scallop] Error: Excess arguments provided: 'baz'"
Is it possible to leave validation for args after a subcommand to the subcommand itself?

**Comment by Rogach** [comment]
The usual approach in such cases is to utilize `--` separator to pass in arguments without any parsing. For example

```scala
class Conf(args: Seq[String]) extends ScallopConf(args) {
  object bar extends Subcommand("bar") {
    val barArgs = trailArg[List[String]]
  }
  addSubcommand(bar)
  verify()
}
// Example call: `program foo -- arg1 arg2 --some-option arg3`
val conf = new Conf(Seq("foo", "--", "arg1", "arg2", "--some-option", "arg3"))
conf.bar.barArgs shoulbBe List("arg1", "arg2", "--some-option", "arg3") // all arguments are passed as-is without parsing
```

 We can't just pass through unknown arguments without explicit end-of-options separator - because we won't be able to do error checking (e.g. was `--bat` a mistyped `--bar` option, or was it meant to be passed through unchanged?).

> If I call `foo bar --help` I'm seeing the help message for foo instead of bar.

Are you sure? If `foo` is the name of scala program here, then help should be printed for the `bar` subcommand (we have a [test for that](https://github.com/scallop/scallop/blob/develop/jvm/src/test/scala/HelpTest.scala#L176)). If it prints the help for the entire program instead then that's a bug.

**Comment by ldeck** [comment]
Thanks @Rogach for your reply. 

Is it possible without using the `--` separator? I'd like to present a fluent api (e.g., awscli), so the call out to another script or not is an implementation detail.

I tried adding `val barArgs = trailArg[List[String]]` to the bar subcommand.

But calling either of the following fails:
```
./bin/foo bar --help
.../bin/foo:9: error: missing argument list for method trailArg in class ScallopConfBase
Unapplied methods are only converted to functions when a function type is expected.
You can make this conversion explicit by writing `trailArg _` or `trailArg(_,_,_,_,_,_,_)(_)` instead of `trailArg`.
    val barArgs = trailArg[List[String]]
```

Or with `--` separator, which I'd like not to do...
```
% ./bin/foo db -- --help
.../bin/foo:9: error: missing argument list for method trailArg in class ScallopConfBase
Unapplied methods are only converted to functions when a function type is expected.
You can make this conversion explicit by writing `trailArg _` or `trailArg(_,_,_,_,_,_,_)(_)` instead of `trailArg`.
    val barArgs = trailArg[List[String]]
```

NB: bar may not be the only subcommand handled intended on being executed by another shell script.

**Comment by Rogach** [comment]
> But calling either of the following fails:

Sorry, I wrote an example without compiling. You need to add parentheses to the call: `trailArg[List[String]]()`.

> Is it possible without using the -- separator?
Unfortunately there's no such functionality in Scallop at the moment, and extending it to turn off option parsing on per-subcommand basis is not trivial.

> I'd like to present a fluent api (e.g., awscli)

I think that awscli actually still validates the arguments before passing them elsewhere - it's simply better UX, since it will be able to show much better error message than a sub-process.

**Comment by ldeck** [comment]
Thanks @Rogach— cool, the function parens works. (Should have checked the docs myself :-)

Yeah okay, I was hoping not to duplicate code as it would mean maintaining inner knowledge of another script. But I can probably figure out a way to make that more convenient.

Thanks for your help!
