### ISSUE TITLE
The appendDefaultToDescription is hard to discover and maybe consider enabling it by default

### ISSUE THREAD

**Issue by Flowdalic** [scallop/scallop#243]
I was surprised that Scallop did not print the default value (if any) per default. Assuming that this feature was missing, I dug into the codebase only to find, to my pleasant surprise, that this feature actually exists.

It is, however, not enabled by default and not documented in the, otherwise excellent, Scallop Wiki.

Please make it easier discoverable and consider enabling it by default (what's the reason that it is disabled by default anyways?).

Thanks for Scallop. It's a great CLI parser for Scala!

**Comment by Rogach** [comment]
It wasn't enabled by default because of backwards compatibility - changing output format is a breaking change, and I strive to take backward compatibility very seriously.

Also I find the selected format (parens with equals) a bit ugly. It was chosen because I perceived it to be the safest to be appended automatically (it doesn't care if there's a dot at the end of option description, for example). While it is the safest, it feels a little out-of-place, and I felt that it's best to leave the precise formatting to the user.

Python's argparse library does it the same way - defaults are not printed by default.

Enabling this behavior by default would also require a breaking change, and I'm against that at the moment (backward compatibility is important, and I don't want to introduce unnecessary update pains on the users).

I've updated the wiki with information about this feature - thanks for the catch!
