### ISSUE TITLE
Argument validation functions do support proprety arguments

### ISSUE THREAD

**Issue by stevedlawrence** [scallop/scallop#244]
For example:

```scala
class Conf(args: Seq[String]) extends ScallopConf(args) {
  val foo = opt[Int]()
  val bars = props[Int]('B')

  conflicts(foo, List(bars))
  verify()
}
```
The idea is to say that if the `foo` option is provided, then no `bars` property arguments can be provided.

This fails to compile because `props` returns a LazyMap which isn't a ScallopOption:
```
[error]  found   : org.rogach.scallop.LazyMap[String,Int]
[error]  required: org.rogach.scallop.ScallopOption[_]
[error]   conflicts(foo, List(bars))
[error]                       ^
```

I believe the other validation functions have the same issue.

It would be nice if we could validate property arguments in a similar way to other scallop options.

**Comment by Rogach** [comment]
I've adjusted argument validation functions to support props as well. Released the new version with this change - `5.1.0`.

`validate` and `validateOpt` functions are unchanged, because they explicitly depend on options being convertible to Options, which isn't easily doable for props. I think that's not a big issue, since such specific use-cases can be handled by using `addValidation` function, which allows one to define arbitrarily complex custom validations.
