### ISSUE TITLE
subcommands require at least one enclosed option or subcommand

### ISSUE THREAD

**Issue by teichert** [scallop/scallop#25]
If I have a subcommand with no enclosed options, I get a runtime exception.
The following works:

```
def main(args: Array[String]) { 
  val opts = new ScallopConf(args) { 
    val mycmd = new Subcommand("mycmd") {
      val dummy = opt[String]("dummy")
    }
  }
  opts.subcommand match {
    case Some(opts.mycmd) => println("mycmd")
    case _ => println("none")
  }
}
```

  sbt "run-main Tools mycmd"

but not the following:

```
def main(args: Array[String]) { 
  val opts = new ScallopConf(args) { 
    val mycmd = new Subcommand("mycmd") {
    }
  }
  opts.subcommand match {
    case Some(opts.mycmd) => println("mycmd")
    case _ => println("none")
  }
}
```

sbt "run-main Tools mycmd"

It gives:

[error](run-main) org.rogach.scallop.exceptions.OptionParseException: Failed to parse the trailing argument list: 'mycmd' org.rogach.scallop.exceptions.OptionParseException: Failed to parse the trailing argument list: 'mycmd' at org.rogach.scallop.Scallop$$anonfun$parseRest$1$4.apply(Scallop.scala:67)

I'm using version 0.6.2

**Comment by Rogach** [comment]
It seems to be a bug. I'll fix it as soon as possible.

In the meanwhile, why do you need an empty subcommand? I feel that you can easily substitute it with a trailing argument:

``` scala
val opts = new ScallopConf(args) {
  val cmd = trailArg[String]("cmd", required = false)
}
opts.cmd.get match {
  case Some("mycmd") => println("mycmd")
  case _ => println("none")
}
```

**Comment by teichert** [comment]
Thanks.  I think I'd prefer to have it be a subcommand so that when I think of more options for the subcommand (or when I decide that I don't need the options in an existing subcommand), I don't have to change the type of option.

**Comment by Rogach** [comment]
Well, that seem to be a good idea. I'll fix it.

**Comment by Rogach** [comment]
Seems that some things are easier to say than to do. In this case, the problem lies in the [AfterInit](https://github.com/Rogach/scallop/blob/master/src/main/scala/org.rogach.scallop/AfterInit.scala) trait.

That trait is used to run some code after subclass initialization - in this case, after all options are specified in your Subcommand. `AfterInit` relies on `DelayedInit` trait, and empty initialization blocks break the count - resulting in the subcommand not being added to the parent config.

I see no way of fixing the problem in the library, but there is an extremely simple workaround - just add something to the body of your subcommand - anything will do, even `()`:

``` scala
val opts = new ScallopConf(args) { 
  val mycmd = new Subcommand("mycmd") {()}
}
```

I've added a test case: 03a70c35d204da
