### ISSUE TITLE
long option with only one "-", e.g.: -out 

### ISSUE THREAD

**Issue by xhudik** [scallop/scallop#45]
Hi, 
is there any possibility how to define long option but with only one "-" (not GNU-style long option names  with 2 "--" ) ?

It is quite common to have arguments like "-in", "-file",...

As your program supports wide range of different arguments styles, not sure whether this "-input" type wouldn't collide with something else ...

thanks, Tomas

**Comment by Rogach** [comment]
Well, `-input` would indeed collide with grouped one-letter arguments - it would be parsed as `-i -n -p -u -t` (5 options). I thought that having the ability to group one-letter options outweighs the ability to write a `-` instead of `--`. Also, it seems to be more widely accepted style (with the notable exception of `java` and related programs).

**Comment by xhudik** [comment]
that's true - thanks

**Comment by Rogach** [comment]
If you _really_ need it, you can achieve the needed effect using a simple hack - just preprocess the arguments array before passing it into Scallop:

``` scala
val options = Set("-input", "-output")
val processedArgs = args.collect {
    case a if options(a) => '-' +: a
    case a => a
  }
val opts = new ScallopConf(processedArgs) {...}
```
