### ISSUE TITLE
make ScallopOption extends (() => Option[A])

### ISSUE THREAD

**Issue by evantill** [scallop/scallop#56]

**Comment by Rogach** [comment]
I'm don't understand that, sorry. What would passed in String mean? As I see it, currently it would be more logical to extend `Function0[A]`, since `ScallopOption.apply()` currently returns `A`.

Can you explain a bit more, please?

**Comment by evantill** [comment]
You are right.

I would like to use my configuration like this :

``` scala
trait MyConf {
  def url:Option[String]
}

object MyScallopConf extends ScallopConf(args) with MyConf {
  val url = opt[String]("url")
}
```

it would be possible if `ScallopOption extends Function0[Option[A]]`

**Comment by Rogach** [comment]
You are trying to provide several alternate ways to parse the same config (MyConf)? As I see it, it would be not possible to achieve that syntax with scallop - the problem lies in the fact that I need to know all the option definitions _before_ parsing the arguments. That's exactly the reason why I can't return `Option[A]` from `opt` call, and `ScallopOption[A]` is used instead. `ScallopOption` defers evaluation of the value until later time.

I think you could do something along this way:

``` scala
trait MyConf {
  def url: Option[String]
}
object MyScallopConf extends ScallopConf(args) with MyConf {
  val urlOpt = opt[String]("url")
  lazy val url = urlOpt.get
}
```

It is quite boilerplaty, though - maybe macros can help you out?

**Comment by evantill** [comment]
ok thank you. If I have some times I will investigate on how to increase the usability
