### ISSUE TITLE
consider short version of subcommand trailing aguments

### ISSUE THREAD

**Issue by hsn10** [scallop/scallop#63]
thing to consider, look for example at git:

```
git push [--all | --mirror | --tags] [-n | --dry-run] [--receive-pack=<git-receive-pack>]
           [--repo=<repository>] [-f | --force] [--prune] [-v | --verbose] [-u | --set-upstream]
           [<repository> [<refspec>…]]

```

trailing argument names are enclosed in <>, optional also enclosed in []

some command are using variant without listed all option names like:

```
git push [options] <repository> [<refspec>]
```

**Comment by Rogach** [comment]
As of now, I intentionally don't generate such usage message - because it's quite flexible, and every developer would want to provide their own format for such line (grouping, omitting some options, etc), so I decided to opt for a bit more flexible approach (using `banner`, which can contain any text you want).

**Comment by hsn10** [comment]
its easy to do it wrong with lot of options. you might add shortCommandHelp() to act like
shortSubcommandsHelp().

**Comment by Rogach** [comment]
I'll need to think about it. There are a lot of things hard to get right - for example, how should those options be ordered? How should I detect stuff like dependences between `all`, `mirror` and `tags` options?

I do like the second form (with options left out), but I still think that it would be better to leave to the developer to tweak the formatting to their liking.

**Comment by Rogach** [comment]
One thought about this proposal:

For example, if somebody specifies the dependencies as:

``` scala
mutuallyExclusive(apples, bananas)
```

I'll format the help line as `[ --apples | --bananas ]`. But what if the specification goes as follows:

``` scala
mutuallyExclusive(apples, bananas)
mutuallyExclusive(apples, coconuts)
```

What will be the summary in this case?

**Comment by hsn10** [comment]
[ --apples | --bananas | --coconuts ]

**Comment by Rogach** [comment]
@hsn10 - that would mean that you can't specify `coconuts` and `bananas` together - which is wrong, since they only have mutual exclusion with `apples`. This would be the valid command line, given the spec:

```
prog --bananas --coconuts
```

**Comment by hsn10** [comment]
i know but i would not go into such deep details during automated help message building. Most programs i seen with hand written help is using this too. For short message its good enough, deeper details are in error message on invocation

**Comment by Rogach** [comment]
Well, I'm not going to settle for "good enough", because then I would be providing user the wrong message. I actually can give you a truckload of such corner cases, so I don't think that it would be good idea to auto-generate such help message.

If you can implement something like this in sane and obvious way, then do a pull request, of course. I won't implement it, because currently it will be error-prone and very confusing - better to leave that part to developer.
