### ISSUE TITLE
boolean default fails

### ISSUE THREAD

**Issue by alexy** [scallop/scallop#8]
```
test ("boolean true default fails") {
  object d extends ScallopConf(List()) {
    val boo = opt[Boolean]("key", descr = "get me a true man", default = Some(true))

    verify
  }

  d.boo() should equal (true)
}
```

**Comment by Rogach** [comment]
I think that using default setting on flag option makes no sense.

In case of `default = Some(true)`, the result will always will be true (not too useful information :) ).

In case of `default = Some(false)`, the result will be the same as it is now.

**Comment by alexy** [comment]
So I tried to set a flag to true without changing the rest of the code, and ended up with:

//  val hashOrder            = opt[Boolean]("hashorder", descr =)
  def hashOrder() = true

I think that not respecting a default = Some(true) is utterly confusing; what harm is there to respect it?

**Comment by Rogach** [comment]
So you just needed to temporarily override the option value - maybe for testing purposes?

For that matter, you can use `opt[Boolean]("").map(_ => true)`.

About disrespecting the default - Boolean in this case means a flag option. The nature of the flag option is that when the option is present on the command line, the value is true, otherwise false - no default value is ever consulted. See the definition of flag converter:

``` scala
  implicit val flagConverter = new ValueConverter[Boolean] {
    def parse(s:List[List[String]]) = s match {
      case Nil :: Nil => Right(Some(true))
      case Nil => Right(Some(false))
      case _ => Left(Unit)
    }

    val manifest = implicitly[Manifest[Boolean]]
    val argType = ArgType.FLAG
  }
```

I can add the explicit default (Some(false)) on boolean options and make that converter return None in case of option not present, but it seems like unnecessary cluttering of the code to me (at least, while you can do the same thing with .map).

And about confusing - for me, setting default value on boolean option is _very_ confusing :)

**Comment by Rogach** [comment]
As an afterthought, you are right - implementing codependencies on options requires me to respect the "default" flag values.

**Comment by alexy** [comment]
I was just thinking that either we disallow default for flags altogether and throw if we see one or respect whatever is there.  Temporary override is one use, more permanent one meaning "I could turn it off if I wanted to but never will in fact but still could".

**Comment by Rogach** [comment]
Right now, I'm going to respect whatever is here.

**Comment by alexy** [comment]
Makes sense.

On Thu, Apr 12, 2012 at 11:20 AM, Rogach
reply@reply.github.com
wrote:

**Comment by Rogach** [comment]
Will work as requested in 0.3.5.
