### ISSUE TITLE
Parameter relationship problem

### ISSUE THREAD

**Issue by NickCody** [scallop/scallop#80]
Great library!

This code allows me to correctly default startDate/endDate as intended, but --help throws an exception.

```
import org.rogach.scallop._;
object Hello extends App {
  val opts = new ScallopConf(args) {
    val startDate = opt[String]("startDate", default=Some("2013-12-01))
    val endDate = opt[String]("endDate", default=Some(startDate()))
  }
}

Exception in thread "main" org.rogach.scallop.exceptions.UnknownOption: Unknown option 'help'
        at org.rogach.scallop.Scallop$$anonfun$5.apply(Scallop.scala:125)
        at org.rogach.scallop.Scallop$$anonfun$5.apply(Scallop.scala:125)
```

Perhaps there is a better way to do this?

Best regards,
Nick

**Comment by Rogach** [comment]
Hi!

I apologize for such a long delay, and hope that this issue didn't trouble you for long time.

I think that the best way to handle such cases will be to handle it in separate method:

``` scala
val opts = new ScallopConf(args) {
  val startDate = opt[String]("startDate", default=Some("2013-12-01"))
  val endDate = opt[String]("endDate", default=None)
  def getEndDate = endDate.get.getOrElse(startDate())
}
```

The problem is that Scallop first assembles information about options, then runs verification on those options, their dependencies and stuff - and in this case help printout is triggered before internal builder is fully verified - and non-verified builder tries to parse input string to determine value of startDate, and obviously fails. It will be really hard to fix that.

**Comment by NickCody** [comment]
Thank you!
