### ISSUE TITLE
accept negative integers as option values

### ISSUE THREAD

**Issue by alexy** [scallop/scallop#9]
When trying to pass -10 as a value to an option, it is reported as an undefined option.  When it is enclosed in quotes or preceded by a backslash, trailing arguments fail to parse.

**Comment by alexy** [comment]
For now I fell back on properties, Int typed ones are handling this well as the minus is mashed against the =.

**Comment by Rogach** [comment]
I plan to rectify this today. I will just parse arguments of the form `-\d.*` as arguments instead of option names (thus, option names starting with a digit would be forbidden). 

This would correctly handle natural numbers, decimal numbers, and even scientific notation.

Typed properties are good, but imagine the frustration of a user, who is required to type `-Dval=-1` :)

**Comment by Rogach** [comment]
Fixed in `master`, will be working in 0.3.5.
