### ISSUE TITLE
how to pass the arg value that start with '-'?

### ISSUE THREAD

**Issue by zfy0701** [scallop/scallop#94]
Hi,

I have a arg named id and its value could start with '-', (e.g. -abcd)

if I do program -i -abcd or program --id -abcd, scallop will report option not found for a because it will think -abcd is another option.

finally I found
program "-i -abcd" would work (though "--id -abcd" wouldn't), I wonder in general what's the best practice to pass value like this?

**Comment by Rogach** [comment]
`program "-i -abcd"` works because for single-letter options scallop supports condensed form, where such command line gets rewritten to `program "-i" " -abcd"`. Note, that you have a leading space passed in.

Currently, the best way will be to somehow "escape" the dash when passing it in. 

As of right now, I don't see an easy way to change that behavior:

Parser could have tested that "-a" option is invalid, and pass "-abcd" as a plain string value. But in that case, if "-a" got to be valid, we are back to current situation - no way to disambiguate between "-abcd" as a value and as option.

**Comment by zfy0701** [comment]
how about support the form like:
--id=-abcd?

is that easier?

**Comment by Rogach** [comment]
Yes, that makes sense. I'll try to add that feature as fast as I can.

**Comment by Rogach** [comment]
Well, as fast as I can is not fast enough :) Anyway, this feature is now implemented in current repo, I will release new version with this functionality.
