### ISSUE TITLE
Any plans for Scala 2.12?

### ISSUE THREAD

**Issue by max-leuthaeuser** [scallop/scallop#99]
Hey,

have you considered updating to 2.12 yet?
I have tried it with 2.12.0-M3 but it will fail due to the dependency to sbt-fmpp which has not seen any update in years.

cheers,
Max

**Comment by Rogach** [comment]
Hi!

I'll try fixing the build and updating today.
About sbt-fmpp - it seems I will have to incorporate it directly into the build, no problem here.

**Comment by max-leuthaeuser** [comment]
Thats awesome - looking forward to it!

**Comment by Rogach** [comment]
I cleaned up the build a bit (decided to go with sbt-boilerplate instead of sbt-fmpp, for example).

It successfully compiles with 2.12.0-M3, but I can't run tests, since scalatest is not released for that scala version (and 2.12.0-M1, which has scalatest, is unable to compile scallop).

So I think I will wait for more stable scala version to come along before publishing new artifacts.

**Comment by max-leuthaeuser** [comment]
Scalatest is available:
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.scalatest%22%20AND%20a%3A%22scalatest_2.12.0-M3%22

**Comment by Rogach** [comment]
Yes, my bad - I was looking for latest scalatest version, 2.2.6. I'll try testing with this version.

**Comment by Rogach** [comment]
Successfully compiled and tested with 2.12.0-M3.

I published new version, `0.9.6`, which includes this scala milestone in cross-compilation. It should be synced to Maven Central shortly.
